server:
    port: 8080
spring:
    mvc:
        view:
            prefix: /html/
            suffix: .html
    #multipart
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 0
            max-file-size: 10Mb
            max-request-size: 100Mb
    #datasource
    datasource:
        url: jdbc:mysql://localhost:3306/myblog?characterEncoding=UTF8
        username: root
        password: Oracle@1024
        type: com.alibaba.druid.pool.DruidDataSource
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20